version: '3'
networks:
  proxy:
    driver: bridge
services:
  traefik:
      image: traefik
      restart: unless-stopped
      command: --api --docker
      networks:
        - proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.vf.localhost"
        - "traefik.port=8080"
  api:
    container_name: vue-forum-api
    build:
      context: .
      dockerfile: ./docker/API.Dev.Dockerfile
    networks:
      - proxy
    volumes:
      - ~/go/src/goVueForum/api:/go/src/goVueForum/api
    restart: always
    depends_on:
      - postgres
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:api-vf.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=3000"
  ui:
    container_name: vue-forum-ui
    build:
      context: .
      dockerfile: ./docker/UI.Dev.Dockerfile
    networks:
      - proxy
    restart: always
    volumes:
      - ./ui/:/app/
    labels:
      - "traefik.backend=ui"
      - "traefik.frontend.rule=Host:ui-vf.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
      - "traefik.frontend.passHostHeader=true"
  postgres:
    container_name: postgres
    image: postgres:10.4
    networks:
      - proxy
    restart: always
    env_file:
      - ~/go/src/goVueForum/docker/postgres.env
    ports:
      - "5432:5432"
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
volumes:
  api: