version: '3'
networks:
  proxy:
services:
  traefik:
      image: traefik
      restart: unless-stopped
      command: --api --docker
      networks:
        - proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.vf.localhost"
        - "traefik.port=8080"
  api:
    container_name: vue-forum-api
    build:
      context: .
      dockerfile: ./docker/API.Dev.Dockerfile
    volumes:
      - ${GOPATH}/src/goVueForum/api:/go/src/goVueForum/api
    restart: always
    networks:
      - proxy
    ports:
      - "3000:3000"
    env_file:
      - ${GOPATH}/src/goVueForum/docker/postgres/postgres.env
    depends_on:
      - postgres
      - redis
      - rabbitMQ
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:api-vf.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=3000"
  ui:
    container_name: vue-forum-ui
    build:
      context: .
      dockerfile: ./docker/UI.Dev.Dockerfile
    networks:
      - proxy
    restart: always
    volumes:
      - ./ui/:/app/
    labels:
      - "traefik.backend=ui"
      - "traefik.frontend.rule=Host:ui-vf.localhost"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
      - "traefik.frontend.passHostHeader=false"
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/postgres/postgres.dockerfile
    networks:
      - proxy
    restart: always
    env_file:
      - ${GOPATH}/src/goVueForum/docker/postgres/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ${GOPATH}/src/goVueForum/api/pgdata:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
  redis:
    container_name: redis
    image: redis:3.2
    networks:
      - proxy
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${GOPATH}/src/goVueForum/.tmp/redis:/data
    labels:
      - "traefik.enable=false"
  rabbitMQ:
    container_name: rabbitMQ
    image: rabbitmq:3.7-management
    networks:
      - proxy
    restart: always
    env_file:
      - ${GOPATH}/src/goVueForum/docker/rabbitmq.env
    ports:
      - "5672:5672"
    labels:
      - "traefik.enable=false"
volumes:
  api:
